// <auto-generated />
using System;
using LogicaAccesoDatos.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(ObligatorioContext))]
    [Migration("20260601224923_AuditoriaPrestamo")]
    partial class AuditoriaPrestamo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObligatorioManuel.Entidades.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEquipo");

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.Prestamo", b =>
                {
                    b.Property<int>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestamo"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAltaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucionPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEquipoVisual")
                        .HasColumnType("int");

                    b.Property<int?>("IdMontura")
                        .HasColumnType("int");

                    b.Property<int?>("IdSocio")
                        .HasColumnType("int");

                    b.Property<int>("IdSocioAltaPrestamo")
                        .HasColumnType("int");

                    b.Property<int?>("IdSocioDevolucionPrestamo")
                        .HasColumnType("int");

                    b.Property<int?>("IdTelescopio")
                        .HasColumnType("int");

                    b.HasKey("IdPrestamo");

                    b.HasIndex("IdEquipoVisual");

                    b.HasIndex("IdMontura");

                    b.HasIndex("IdSocio");

                    b.HasIndex("IdTelescopio");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.Socio", b =>
                {
                    b.Property<int>("IdSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSocio"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSocio");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.EquipoVisual", b =>
                {
                    b.HasBaseType("ObligatorioManuel.Entidades.Equipo");

                    b.HasDiscriminator().HasValue("EquipoVisual");
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.Montura", b =>
                {
                    b.HasBaseType("ObligatorioManuel.Entidades.Equipo");

                    b.Property<double>("CargaUtil")
                        .HasColumnType("float");

                    b.Property<bool>("EsComputarizada")
                        .HasColumnType("bit");

                    b.Property<int>("TipoMontura")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Montura");
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.Telescopio", b =>
                {
                    b.HasBaseType("ObligatorioManuel.Entidades.Equipo");

                    b.Property<int>("Apertura")
                        .HasColumnType("int");

                    b.Property<int>("DistanciaFocal")
                        .HasColumnType("int");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("RelacionFocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Telescopio");
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.Camara", b =>
                {
                    b.HasBaseType("ObligatorioManuel.Entidades.EquipoVisual");

                    b.Property<string>("Resolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TamanioPixel")
                        .HasColumnType("float");

                    b.Property<int>("TipoSensor")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camara");
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.Ocular", b =>
                {
                    b.HasBaseType("ObligatorioManuel.Entidades.EquipoVisual");

                    b.Property<int>("AnguloVision")
                        .HasColumnType("int");

                    b.Property<int>("Diametro")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Ocular");
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.Prestamo", b =>
                {
                    b.HasOne("ObligatorioManuel.Entidades.EquipoVisual", "EquipoVisual")
                        .WithMany()
                        .HasForeignKey("IdEquipoVisual");

                    b.HasOne("ObligatorioManuel.Entidades.Montura", "Montura")
                        .WithMany()
                        .HasForeignKey("IdMontura");

                    b.HasOne("ObligatorioManuel.Entidades.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio");

                    b.HasOne("ObligatorioManuel.Entidades.Telescopio", "Telescopio")
                        .WithMany()
                        .HasForeignKey("IdTelescopio");

                    b.Navigation("EquipoVisual");

                    b.Navigation("Montura");

                    b.Navigation("Socio");

                    b.Navigation("Telescopio");
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.Socio", b =>
                {
                    b.OwnsOne("ObligatorioManuel.ValueObjects.SocioContrasenia", "Contrasenia", b1 =>
                        {
                            b1.Property<int>("SocioIdSocio")
                                .HasColumnType("int");

                            b1.Property<string>("Contrasenia")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SocioIdSocio");

                            b1.ToTable("Socios");

                            b1.WithOwner()
                                .HasForeignKey("SocioIdSocio");
                        });

                    b.OwnsOne("ObligatorioManuel.ValueObjects.SocioEmail", "Email", b1 =>
                        {
                            b1.Property<int>("SocioIdSocio")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SocioIdSocio");

                            b1.ToTable("Socios");

                            b1.WithOwner()
                                .HasForeignKey("SocioIdSocio");
                        });

                    b.Navigation("Contrasenia")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
