// <auto-generated />
using LogicaAccesoDatos.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(ObligatorioContext))]
    [Migration("20260419004645_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObligatorioManuel.Entidades.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("ObligatorioManuel.Entidades.Socio", b =>
                {
                    b.OwnsOne("ObligatorioManuel.ValueObjects.SocioContrasenia", "Contrasenia", b1 =>
                        {
                            b1.Property<int>("SocioId")
                                .HasColumnType("int");

                            b1.Property<string>("Contrasenia")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SocioId");

                            b1.ToTable("Socios");

                            b1.WithOwner()
                                .HasForeignKey("SocioId");
                        });

                    b.Navigation("Contrasenia")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
